import { getSupabase } from './supabase'
import {
  clearOutboxItem, getInspection, getObservation, getPhoto, getRemoteId, getVoiceNote,
  listOutbox, markOutboxError, setRemoteId, setSyncState,
  type LocalInspection,
} from './db'

/**
 * Outbox drain.
 *
 * The local model is deliberately denormalised — one inspection row carries the
 * address and the homeowner's details, because that is what a rep fills in on a
 * driveway. The database is normalised: customers, properties and inspections
 * are separate tables. This module is where those two shapes meet, and most of
 * its work is resolving a flat local record into the three remote rows it
 * implies without creating duplicates when a push is retried.
 *
 * Every step records its remote id locally, so a retry after a dropped
 * connection updates rather than inserting a second copy. That matters more
 * than speed here: a duplicated property would put two competing records of the
 * same roof in front of the office.
 */

export interface SyncResult {
  pushed: number
  failed: number
  errors: string[]
  skipped: 'offline' | 'no-session' | 'no-membership' | null
}

const UNIQUE_VIOLATION = '23505'

function fullName(i: LocalInspection): string | null {
  const name = [i.customerFirstName, i.customerLastName].filter(Boolean).join(' ').trim()
  return name || i.customerCompanyName || null
}

/** Ensures the customer row exists, returning its remote id (or null if there is no name to file under). */
async function ensureCustomer(i: LocalInspection, orgId: string): Promise<string | null> {
  const existing = await getRemoteId('customer', i.id)
  if (existing) return existing
  if (!fullName(i)) return null

  const supabase = getSupabase()
  if (!supabase) return null

  const { data, error } = await supabase
    .from('customers')
    .insert({
      organization_id: orgId,
      first_name: i.customerFirstName ?? null,
      last_name: i.customerLastName ?? null,
      company_name: i.customerCompanyName ?? null,
      primary_phone: i.customerPhone ?? null,
      email: i.customerEmail ?? null,
    })
    .select('id')
    .single()

  if (error) throw new Error(`customer: ${error.message}`)
  await setRemoteId('customer', i.id, data.id as string)
  return data.id as string
}

/**
 * Ensures the property row exists.
 *
 * `properties` has a unique index on (organization_id, normalized_address),
 * and normalized_address is generated by the database. We cannot compute it
 * client-side identically, so rather than guess we insert and treat a unique
 * violation as "someone already filed this roof" — then look it up. That keeps
 * the database as the single authority on what counts as the same address.
 */
async function ensureProperty(i: LocalInspection, orgId: string): Promise<string> {
  const existing = await getRemoteId('property', i.id)
  if (existing) return existing

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const payload = {
    organization_id: orgId,
    address_line1: i.addressLine1 ?? 'Unknown address',
    city: i.city ?? null,
    parish: i.parish ?? null,
    postal_code: i.postalCode ?? null,
    property_type: i.propertyType,
    stories: i.stories ?? null,
    roof_material: i.roofMaterial,
    location:
      i.latitude !== undefined && i.longitude !== undefined
        ? `SRID=4326;POINT(${i.longitude} ${i.latitude})`
        : null,
  }

  const { data, error } = await supabase.from('properties').insert(payload).select('id').single()

  if (!error && data) {
    await setRemoteId('property', i.id, data.id as string)
    return data.id as string
  }

  if (error && error.code === UNIQUE_VIOLATION) {
    const { data: found, error: findErr } = await supabase
      .from('properties')
      .select('id')
      .eq('organization_id', orgId)
      .eq('address_line1', payload.address_line1)
      .limit(1)
      .maybeSingle()
    if (findErr || !found) throw new Error(`property lookup: ${findErr?.message ?? 'not found'}`)
    await setRemoteId('property', i.id, found.id as string)
    return found.id as string
  }

  throw new Error(`property: ${error?.message ?? 'unknown'}`)
}

async function ensureInspection(localId: string, orgId: string, userId: string): Promise<string> {
  const existing = await getRemoteId('inspection', localId)
  if (existing) return existing

  const i = await getInspection(localId)
  if (!i) throw new Error('inspection missing locally')

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const customerId = await ensureCustomer(i, orgId)
  const propertyId = await ensureProperty(i, orgId)

  const { data, error } = await supabase
    .from('inspections')
    .insert({
      organization_id: orgId,
      property_id: propertyId,
      customer_id: customerId,
      inspector_id: userId,
      status: i.status === 'complete' ? 'complete' : 'in_progress',
      started_at: i.createdAt,
      completed_at: i.completedAt ?? null,
      roof_material: i.roofMaterial,
      stories: i.stories ?? null,
      homeowner_stated_roof_age_years: i.homeownerStatedRoofAgeYears ?? null,
      homeowner_stated_insurer: i.homeownerStatedInsurer ?? null,
      inspector_recommendation: i.inspectorRecommendation ?? null,
      start_location:
        i.latitude !== undefined && i.longitude !== undefined
          ? `SRID=4326;POINT(${i.longitude} ${i.latitude})`
          : null,
    })
    .select('id')
    .single()

  if (error) throw new Error(`inspection: ${error.message}`)
  await setRemoteId('inspection', localId, data.id as string)
  await setSyncState('inspections', localId, 'synced')
  return data.id as string
}

async function pushPhoto(localId: string, orgId: string, userId: string): Promise<void> {
  if (await getRemoteId('photo', localId)) return
  const photo = await getPhoto(localId)
  if (!photo) throw new Error('photo missing locally')

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const inspectionId = await ensureInspection(photo.inspectionId, orgId, userId)
  const propertyId = (await getRemoteId('property', photo.inspectionId)) ?? 'unknown'

  // Path encodes the org as the second segment; the storage policy reads it
  // back with storage.foldername(name)[2] to decide access.
  const path = `organization/${orgId}/jobs/${propertyId}/inspections/${inspectionId}/photos/${photo.id}.jpg`

  const { error: upErr } = await supabase.storage
    .from('inspection-photos')
    .upload(path, photo.blob, { contentType: 'image/jpeg', upsert: true })
  if (upErr) throw new Error(`upload: ${upErr.message}`)

  const { data, error } = await supabase
    .from('photos')
    .insert({
      organization_id: orgId,
      inspection_id: inspectionId,
      property_id: propertyId,
      captured_by: userId,
      storage_path: path,
      client_id: photo.id,
      byte_size: photo.byteSize,
      width: photo.width,
      height: photo.height,
      captured_at: photo.capturedAt,
      category: photo.category,
      area: photo.area ?? null,
      quality_flag: photo.qualityFlag ?? null,
      retake_recommended: photo.retakeRecommended,
      upload_state: 'uploaded',
      uploaded_at: new Date().toISOString(),
      location:
        photo.latitude !== undefined && photo.longitude !== undefined
          ? `SRID=4326;POINT(${photo.longitude} ${photo.latitude})`
          : null,
    })
    .select('id')
    .single()

  if (error) throw new Error(`photo row: ${error.message}`)
  await setRemoteId('photo', localId, data.id as string)
  await setSyncState('photos', localId, 'synced')
}

async function pushObservation(localId: string, orgId: string, userId: string): Promise<void> {
  if (await getRemoteId('observation', localId)) return
  const o = await getObservation(localId)
  if (!o) throw new Error('observation missing locally')

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const inspectionId = await ensureInspection(o.inspectionId, orgId, userId)
  const { data, error } = await supabase
    .from('inspection_observations')
    .insert({
      organization_id: orgId,
      inspection_id: inspectionId,
      area: o.area ?? null,
      component: o.component ?? null,
      finding: o.finding,
      severity: o.severity,
      source: o.source,
      confirmed_by: o.confirmedAt ? userId : null,
      confirmed_at: o.confirmedAt ?? null,
    })
    .select('id')
    .single()

  if (error) throw new Error(`observation: ${error.message}`)
  await setRemoteId('observation', localId, data.id as string)
  await setSyncState('observations', localId, 'synced')
}

async function pushVoiceNote(localId: string, orgId: string, userId: string): Promise<void> {
  if (await getRemoteId('voiceNote', localId)) return
  const v = await getVoiceNote(localId)
  if (!v) throw new Error('voice note missing locally')

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const inspectionId = await ensureInspection(v.inspectionId, orgId, userId)
  const path = `organization/${orgId}/inspections/${inspectionId}/voice/${v.id}.webm`

  const { error: upErr } = await supabase.storage
    .from('inspection-photos')
    .upload(path, v.blob, { contentType: v.blob.type || 'audio/webm', upsert: true })
  if (upErr) throw new Error(`voice upload: ${upErr.message}`)

  const { data, error } = await supabase
    .from('voice_notes')
    .insert({
      organization_id: orgId,
      inspection_id: inspectionId,
      recorded_by: userId,
      client_id: v.id,
      storage_path: path,
      duration_seconds: v.durationSeconds,
      transcript: v.transcript ?? null,
      recorded_at: v.recordedAt,
      upload_state: 'uploaded',
    })
    .select('id')
    .single()

  if (error) throw new Error(`voice row: ${error.message}`)
  await setRemoteId('voiceNote', localId, data.id as string)
  await setSyncState('voiceNotes', localId, 'synced')
}

/**
 * Drains the outbox once. Safe to call repeatedly and safe to interrupt: each
 * item is independent, and anything that fails stays queued with its error
 * recorded rather than being silently dropped.
 */
export async function syncOutbox(orgId: string | null, userId: string | null): Promise<SyncResult> {
  const result: SyncResult = { pushed: 0, failed: 0, errors: [], skipped: null }

  if (!navigator.onLine) return { ...result, skipped: 'offline' }
  if (!userId) return { ...result, skipped: 'no-session' }
  if (!orgId) return { ...result, skipped: 'no-membership' }
  if (!getSupabase()) return { ...result, skipped: 'no-session' }

  // Inspections first: everything else references one, and pushing a photo
  // before its inspection would just fail and re-queue.
  const items = await listOutbox()
  const ordered = [
    ...items.filter((i) => i.entity === 'inspection'),
    ...items.filter((i) => i.entity !== 'inspection'),
  ]

  for (const item of ordered) {
    try {
      if (item.entity === 'inspection') await ensureInspection(item.entityId, orgId, userId)
      else if (item.entity === 'photo') await pushPhoto(item.entityId, orgId, userId)
      else if (item.entity === 'observation') await pushObservation(item.entityId, orgId, userId)
      else if (item.entity === 'voiceNote') await pushVoiceNote(item.entityId, orgId, userId)
      await clearOutboxItem(item.id)
      result.pushed += 1
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      await markOutboxError(item.id, message)
      result.failed += 1
      if (result.errors.length < 5) result.errors.push(`${item.entity}: ${message}`)
    }
  }

  return result
}
