import { getSupabase } from '../supabase'
import { getRemoteId, markSynced, readInspection, setRemoteId } from '../sync-store'
import type { LocalInspection } from '../db'

/**
 * Resolves a flat local inspection into the three remote rows it implies.
 *
 * The local model is deliberately denormalised — one row carries the address
 * and the homeowner's details, because that is what a rep fills in standing on
 * a driveway. The database is normalised into customers, properties and
 * inspections. Bridging the two without duplicating anything on a retry is the
 * whole job here.
 */

const UNIQUE_VIOLATION = '23505'

function pointOrNull(lat?: number, lon?: number): string | null {
  return lat !== undefined && lon !== undefined ? `SRID=4326;POINT(${lon} ${lat})` : null
}

function fullName(i: LocalInspection): string | null {
  const n = [i.customerFirstName, i.customerLastName].filter(Boolean).join(' ').trim()
  return n || i.customerCompanyName || null
}

async function ensureCustomer(i: LocalInspection, orgId: string): Promise<string | null> {
  const existing = await getRemoteId('customer', i.id)
  if (existing) return existing
  if (!fullName(i)) return null

  const supabase = getSupabase()
  if (!supabase) return null

  const { data, error } = await supabase
    .from('customers')
    .insert({
      organization_id: orgId,
      first_name: i.customerFirstName ?? null,
      last_name: i.customerLastName ?? null,
      company_name: i.customerCompanyName ?? null,
      primary_phone: i.customerPhone ?? null,
      email: i.customerEmail ?? null,
    })
    .select('id')
    .single()

  if (error) throw new Error(`customer: ${error.message}`)
  await setRemoteId('customer', i.id, data.id as string)
  return data.id as string
}

/**
 * `properties` is unique on (organization_id, normalized_address), and
 * normalized_address is generated by the database. We cannot reproduce it
 * client-side, so rather than guess we insert and treat a unique violation as
 * "this roof is already on file", then look it up. The database stays the only
 * authority on what counts as the same address.
 */
async function ensureProperty(i: LocalInspection, orgId: string): Promise<string> {
  const existing = await getRemoteId('property', i.id)
  if (existing) return existing

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const address = i.addressLine1 ?? 'Unknown address'
  const { data, error } = await supabase
    .from('properties')
    .insert({
      organization_id: orgId,
      address_line1: address,
      city: i.city ?? null,
      parish: i.parish ?? null,
      postal_code: i.postalCode ?? null,
      property_type: i.propertyType,
      stories: i.stories ?? null,
      roof_material: i.roofMaterial,
      location: pointOrNull(i.latitude, i.longitude),
    })
    .select('id')
    .single()

  if (!error && data) {
    await setRemoteId('property', i.id, data.id as string)
    return data.id as string
  }

  if (error?.code === UNIQUE_VIOLATION) {
    const { data: found, error: findErr } = await supabase
      .from('properties')
      .select('id')
      .eq('organization_id', orgId)
      .eq('address_line1', address)
      .limit(1)
      .maybeSingle()
    if (findErr || !found) throw new Error(`property lookup: ${findErr?.message ?? 'not found'}`)
    await setRemoteId('property', i.id, found.id as string)
    return found.id as string
  }

  throw new Error(`property: ${error?.message ?? 'unknown'}`)
}

/** Returns the remote inspection id, creating the customer and property first. */
export async function ensureInspection(localId: string, orgId: string, userId: string): Promise<string> {
  const existing = await getRemoteId('inspection', localId)
  if (existing) return existing

  const i = await readInspection(localId)
  if (!i) throw new Error('inspection missing locally')

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const customerId = await ensureCustomer(i, orgId)
  const propertyId = await ensureProperty(i, orgId)

  const { data, error } = await supabase
    .from('inspections')
    .insert({
      organization_id: orgId,
      property_id: propertyId,
      customer_id: customerId,
      inspector_id: userId,
      status: i.status === 'complete' ? 'complete' : 'in_progress',
      started_at: i.createdAt,
      completed_at: i.completedAt ?? null,
      roof_material: i.roofMaterial,
      stories: i.stories ?? null,
      homeowner_stated_roof_age_years: i.homeownerStatedRoofAgeYears ?? null,
      homeowner_stated_insurer: i.homeownerStatedInsurer ?? null,
      inspector_recommendation: i.inspectorRecommendation ?? null,
      start_location: pointOrNull(i.latitude, i.longitude),
    })
    .select('id')
    .single()

  if (error) throw new Error(`inspection: ${error.message}`)
  await setRemoteId('inspection', localId, data.id as string)
  await markSynced('inspections', localId, 'synced')
  return data.id as string
}

export { pointOrNull }
