import { getSupabase } from '../supabase'
import { getRemoteId, markSynced, readInspection, setRemoteId } from '../sync-store'
import { propertyMatchKey } from '../address'
import type { LocalInspection } from '../db'

/**
 * Resolves a flat local inspection into the three remote rows it implies.
 *
 * The local model is deliberately denormalised — one row carries the address
 * and the homeowner's details, because that is what a rep fills in standing on
 * a driveway. The database is normalised into customers, properties and
 * inspections. Bridging the two without duplicating anything on a retry is the
 * whole job here.
 */

const UNIQUE_VIOLATION = '23505'

function pointOrNull(lat?: number, lon?: number): string | null {
  return lat !== undefined && lon !== undefined ? `SRID=4326;POINT(${lon} ${lat})` : null
}

function fullName(i: LocalInspection): string | null {
  const n = [i.customerFirstName, i.customerLastName].filter(Boolean).join(' ').trim()
  return n || i.customerCompanyName || null
}

/**
 * The remote status this local inspection implies.
 *
 * Kept as a pure function because it is the one place where a later push could
 * silently walk back progress: an inspection that has already been handed to
 * the office must never be downgraded to 'complete' just because the rep edited
 * a phone number afterwards and triggered another push.
 */
export function remoteStatusFor(i: Pick<LocalInspection, 'status' | 'sentToOfficeAt'>): string {
  if (i.sentToOfficeAt) return 'sent_to_office'
  return i.status === 'complete' ? 'complete' : 'in_progress'
}

async function ensureCustomer(i: LocalInspection, orgId: string): Promise<string | null> {
  const existing = await getRemoteId('customer', i.id)
  if (existing) return existing
  if (!fullName(i)) return null

  const supabase = getSupabase()
  if (!supabase) return null

  const { data, error } = await supabase
    .from('customers')
    .insert({
      organization_id: orgId,
      first_name: i.customerFirstName ?? null,
      last_name: i.customerLastName ?? null,
      company_name: i.customerCompanyName ?? null,
      primary_phone: i.customerPhone ?? null,
      email: i.customerEmail ?? null,
    })
    .select('id')
    .single()

  if (error) throw new Error(`customer: ${error.message}`)
  await setRemoteId('customer', i.id, data.id as string)
  return data.id as string
}

/**
 * `properties` is unique on (organization_id, normalized_address), and
 * normalized_address is generated by the database. We cannot insert it, so
 * rather than guess we insert and treat a unique violation as "this roof is
 * already on file", then look it up by the same normalised key the database
 * computed — see `src/lib/address.ts` for why that mirror exists.
 */
export interface PropertySeed {
  /** The local record this property is being resolved for. Cache key only. */
  localId: string
  addressLine1: string
  city?: string | undefined
  parish?: string | undefined
  postalCode?: string | undefined
  latitude?: number | undefined
  longitude?: number | undefined
  propertyType?: string | undefined
  roofMaterial?: string | undefined
  stories?: number | undefined
}

/**
 * Shared by inspections and leads, because they are the same roof.
 *
 * A rep knocks a door, records the conversation, and later inspects it. Those
 * are two local records of one property, and both resolve through here to the
 * same remote row via the normalised address — which is the only reason the
 * office does not end up with the lead history on one property and the photos
 * on a duplicate of it.
 */
export async function ensurePropertyFor(seed: PropertySeed, orgId: string): Promise<string> {
  const existing = await getRemoteId('property', seed.localId)
  if (existing) return existing

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const address = seed.addressLine1
  const { data, error } = await supabase
    .from('properties')
    .insert({
      organization_id: orgId,
      address_line1: address,
      city: seed.city ?? null,
      parish: seed.parish ?? null,
      postal_code: seed.postalCode ?? null,
      property_type: seed.propertyType ?? 'residential',
      stories: seed.stories ?? null,
      roof_material: seed.roofMaterial ?? 'unknown',
      location: pointOrNull(seed.latitude, seed.longitude),
    })
    .select('id')
    .single()

  if (!error && data) {
    await setRemoteId('property', seed.localId, data.id as string)
    return data.id as string
  }

  if (error?.code === UNIQUE_VIOLATION) {
    const key = propertyMatchKey(address, seed.postalCode ?? null)
    const { data: found, error: findErr } = await supabase
      .from('properties')
      .select('id')
      .eq('organization_id', orgId)
      .eq('normalized_address', key)
      .limit(1)
      .maybeSingle()
    if (findErr || !found) throw new Error(`property lookup: ${findErr?.message ?? 'not found'}`)
    await setRemoteId('property', seed.localId, found.id as string)
    return found.id as string
  }

  throw new Error(`property: ${error?.message ?? 'unknown'}`)
}

async function ensureProperty(i: LocalInspection, orgId: string): Promise<string> {
  return ensurePropertyFor(
    {
      localId: i.id,
      addressLine1: i.addressLine1 ?? 'Unknown address',
      city: i.city,
      parish: i.parish,
      postalCode: i.postalCode,
      latitude: i.latitude,
      longitude: i.longitude,
      propertyType: i.propertyType,
      roofMaterial: i.roofMaterial,
      stories: i.stories,
    },
    orgId,
  )
}

/**
 * Pushes the inspection's CURRENT state and returns its remote id.
 *
 * This upserts on every call rather than short-circuiting when a remote id is
 * already known. That is the fix for the bug where an inspection reached the
 * server once, at creation, and every subsequent edit — completion time,
 * recommendation, homeowner-stated roof age, override note — stayed on the
 * phone. The office saw an inspection that was permanently in progress.
 *
 * The conflict target is (organization_id, client_id), so a retry after an
 * acknowledgement was lost updates the existing row instead of creating a
 * second inspection of the same roof.
 */
export async function ensureInspection(localId: string, orgId: string, userId: string): Promise<string> {
  const i = await readInspection(localId)
  if (!i) throw new Error('inspection missing locally')

  const supabase = getSupabase()
  if (!supabase) throw new Error('not configured')

  const customerId = await ensureCustomer(i, orgId)
  const propertyId = await ensureProperty(i, orgId)

  const { data, error } = await supabase
    .from('inspections')
    .upsert(
      {
        organization_id: orgId,
        client_id: i.id,
        property_id: propertyId,
        customer_id: customerId,
        inspector_id: userId,
        status: remoteStatusFor(i),
        started_at: i.createdAt,
        completed_at: i.completedAt ?? null,
        roof_material: i.roofMaterial,
        stories: i.stories ?? null,
        homeowner_stated_roof_age_years: i.homeownerStatedRoofAgeYears ?? null,
        homeowner_stated_insurer: i.homeownerStatedInsurer ?? null,
        inspector_recommendation: i.inspectorRecommendation ?? null,
        overridden_issue_codes: i.overriddenIssueCodes ?? [],
        override_note: i.overrideNote ?? null,
        start_location: pointOrNull(i.latitude, i.longitude),
      },
      { onConflict: 'organization_id,client_id' },
    )
    .select('id')
    .single()

  if (error) throw new Error(`inspection: ${error.message}`)
  await setRemoteId('inspection', localId, data.id as string)
  await markSynced('inspections', localId, 'synced')
  return data.id as string
}

/**
 * Per-drain memo around `ensureInspection`.
 *
 * Every photo, observation and voice note needs the remote inspection id, and
 * without this a drain of forty photos would upsert the same inspection forty
 * times. The cache lives for one drain only, so the next drain still pushes the
 * rep's latest edits.
 */
export function inspectionResolver(orgId: string, userId: string) {
  const cache = new Map<string, Promise<string>>()
  return (localId: string): Promise<string> => {
    const hit = cache.get(localId)
    if (hit) return hit
    const p = ensureInspection(localId, orgId, userId)
    cache.set(localId, p)
    return p
  }
}

export type InspectionResolver = ReturnType<typeof inspectionResolver>

export { pointOrNull }
