/**
 * What this software is not allowed to say.
 *
 * Every other safeguard in this codebase protects a fact. This one protects a
 * promise — and promises are where roofing contractors get sued, lose licences,
 * and end up in state attorney-general consent orders. A rep who overstates a
 * measurement has made a mistake. A rep who tells a homeowner "insurance will
 * pay for all of this" has made a representation the company cannot honour,
 * about money that is not the company's to commit, on behalf of a carrier that
 * has not been asked.
 *
 * The rule is narrow and absolute: nothing generated by this system — proposal
 * copy, an AI approach script, a claim summary, a text message draft — asserts
 * that a claim will be approved, that insurance will pay, or that a cost will
 * be covered. Not hedged, not "typically", not "in our experience". The check
 * runs on the finished string, after any model has written it, because the
 * point of failure is the sentence that reaches the homeowner and nothing
 * upstream of it.
 *
 * WHAT IS BANNED AND WHAT IS NOT
 *
 * This is not a ban on discussing insurance. "We will document this for your
 * carrier" is fine and is the actual product. "Your deductible is what you pay"
 * is fine. What is banned is the SPEECH ACT of guaranteeing an outcome
 * controlled by somebody else. The distinction the patterns below draw is
 * between describing a process and promising its result.
 *
 * A second, quieter category is banned too: claims of universal success
 * ("we win every claim", "we beat every competitor"). Those are not merely
 * distasteful, they are unprovable comparative advertising, and a competitor
 * can complain about them to the same regulator.
 */

export type ViolationKind =
  /** Promises a carrier will pay, approve, or cover. */
  | 'guarantees_coverage'
  /** Claims a perfect or universal record. */
  | 'guarantees_success'
  /** Tells the homeowner the deductible will be absorbed, waived or covered. */
  | 'deductible_inducement'
  /** Asserts damage or causation the evidence has not established. */
  | 'asserts_unproven_damage'
  /** Manufactures urgency to force a signature. */
  | 'false_urgency'

export interface Violation {
  readonly kind: ViolationKind
  /** The phrase as it appeared, so a person can find and fix it. */
  readonly matched: string
  /** Why this cannot be said, in one sentence. */
  readonly because: string
  /** Something true that does the same job. */
  readonly insteadSay: string
}

interface Rule {
  readonly kind: ViolationKind
  readonly pattern: RegExp
  readonly because: string
  readonly insteadSay: string
}

const RULES: readonly Rule[] = [
  {
    kind: 'guarantees_coverage',
    // "insurance will pay", "your carrier will cover", "they'll pay for it all"
    pattern:
      /\b(insurance|insurer|carrier|they|state\s+farm|allstate|usaa)\b[^.?!]{0,40}\b(will|gonna|going\s+to|is\s+going\s+to)\b[^.?!]{0,20}\b(pay|cover|approve|take\s+care\s+of)\b/i,
    because:
      'Whether a carrier pays is the carrier’s decision, made against a policy this company has not read, for a loss it has not adjusted.',
    insteadSay:
      'We document the damage and the storm evidence and give your carrier a complete package to review.',
  },
  {
    kind: 'guarantees_coverage',
    pattern: /\b(fully|100%|completely|entirely)\s+covered\b/i,
    because: 'Coverage depends on the policy, the date of loss and the adjuster’s findings.',
    insteadSay: 'Your policy and the adjuster’s findings decide what is covered.',
  },
  {
    kind: 'guarantees_coverage',
    pattern: /\b(guarantee|guaranteed|guaranteeing)\b[^.?!]{0,30}\b(approv\w+|coverage|covered|claim|payment|paid)\b/i,
    because: 'No contractor can guarantee a claim outcome.',
    insteadSay: 'We can tell you how strong the documentation is, and what is still uncertain.',
  },
  {
    kind: 'guarantees_coverage',
    pattern: /\b(claim\s+will\s+be\s+approved|approval\s+is\s+guaranteed|we\s+will\s+get\s+(this|it|your\s+claim)\s+approved)\b/i,
    because: 'Approval is the carrier’s decision, not a prediction this company may make.',
    insteadSay: 'We will put the strongest accurate evidence in front of your carrier.',
  },
  {
    kind: 'guarantees_success',
    pattern: /\b(we|delta\s*ridge)\b[^.?!]{0,30}\b(never\s+lose|win\s+(every|them\s+all|100%)|always\s+win|100%\s+(approval|success)\s+rate)\b/i,
    because: 'A universal success claim is unprovable and is comparative advertising a competitor can complain about.',
    insteadSay:
      'We find missing documentation, measurement differences and legitimate supplement opportunities.',
  },
  {
    kind: 'guarantees_success',
    pattern: /\b(beat|better\s+than|destroy|crush)\s+(every|all|any)\s+(other\s+)?(competitor|contractor|roofer|company)\b/i,
    because: 'An unprovable comparison against every competitor is not a claim this company can support.',
    insteadSay:
      'Here is exactly what our documentation includes, so you can compare it to anyone else’s.',
  },
  {
    kind: 'deductible_inducement',
    /*
     * Offering to absorb, waive or rebate a deductible is a criminal offence in
     * a number of states and a licence matter in most of the rest. It is also
     * the single most common thing a storm-chasing rep says, which is why it is
     * checked here rather than trusted to training.
     */
    pattern: /\b(waive|waiv\w+|cover|absorb|eat|forget\s+about|no\s+need\s+to\s+pay)\b[^.?!]{0,25}\bdeductible\b/i,
    because:
      'Absorbing or waiving a homeowner’s deductible is insurance fraud in many states and a licensing matter in most others.',
    insteadSay: 'Your deductible is the part you pay. We can show you exactly what it applies to.',
  },
  {
    kind: 'deductible_inducement',
    pattern: /\bdeductible\b[^.?!]{0,25}\b(on\s+us|free|waived|covered\s+by\s+us)\b/i,
    because: 'A deductible cannot be absorbed by the contractor.',
    insteadSay: 'Your deductible is the part you pay.',
  },
  {
    kind: 'asserts_unproven_damage',
    // "the hail hit your roof", "your roof was damaged by the storm"
    pattern:
      /\b(your|this)\s+roof\b[^.?!]{0,30}\b(was|is|has\s+been)\s+(damaged|destroyed|totalled|totaled)\b/i,
    because:
      'Damage at a specific address is established by inspection, not by a storm having passed nearby.',
    insteadSay:
      'There was documented hail in the area, and we can look at whether this roof shows related conditions.',
  },
  {
    kind: 'asserts_unproven_damage',
    pattern: /\b(\d+(\.\d+)?)\s*(in(ch(es)?)?|")\s+hail\s+(hit|struck|fell\s+on)\s+(your|this)\s+(house|home|roof|property)\b/i,
    because:
      'A hail report describes where a person observed hail, not what fell on one particular roof.',
    insteadSay: 'Hail of that size was officially reported nearby — the report gives the distance.',
  },
  {
    kind: 'asserts_unproven_damage',
    pattern: /\b(you\s+(definitely|certainly)\s+(have|need)|you\s+need\s+a\s+new\s+roof)\b/i,
    because: 'Whether a roof needs replacing is a conclusion from an inspection, not an opening line.',
    insteadSay: 'We can document the roof’s condition and show you what we find.',
  },
  {
    kind: 'false_urgency',
    pattern: /\b(sign\s+(today|now|right\s+now)|only\s+good\s+(today|until)|last\s+chance|before\s+(it'?s\s+)?too\s+late)\b/i,
    because: 'Manufactured deadlines are a deceptive sales practice under the FTC Telemarketing Sales Rule.',
    insteadSay:
      'There are real deadlines in a policy — we can tell you what yours are and where to read them.',
  },
]

export type LanguageCheck =
  | { readonly ok: true }
  | { readonly ok: false; readonly violations: readonly Violation[] }

/**
 * Check finished copy before a person sees it.
 *
 * Runs on the output string rather than on a prompt, because a model asked
 * nicely not to promise things will still do so under the right phrasing, and
 * because copy also arrives from templates, from a rep typing, and from a field
 * pasted out of somebody's old proposal.
 */
export function checkLanguage(text: string): LanguageCheck {
  const violations: Violation[] = []
  for (const rule of RULES) {
    const match = rule.pattern.exec(text)
    if (match !== null) {
      violations.push({
        kind: rule.kind,
        matched: match[0].trim(),
        because: rule.because,
        insteadSay: rule.insteadSay,
      })
    }
  }
  return violations.length === 0 ? { ok: true } : { ok: false, violations }
}

/**
 * Whether claim-related language is supportable at all yet.
 *
 * Separate from the wording check. Even impeccably hedged copy about storm
 * damage is not honest when the only imagery is four years old and the storm
 * was in March — so this gates on the evidence rather than on the phrasing, and
 * both have to pass.
 */
export interface EvidencePosture {
  readonly stormTier: 'A' | 'B' | 'C' | 'D' | 'E'
  /** Whether imagery exists that post-dates the storm. */
  readonly hasPostStormImagery: boolean
  /** Whether anybody has actually looked at the roof, remotely or in person. */
  readonly roofInspected: boolean
}

export type CopyStrength =
  /** Evidence supports discussing documented damage. */
  | 'documented'
  /** Evidence supports discussing the storm, not this roof. */
  | 'storm_only'
  /** Nothing yet supports a damage conversation. */
  | 'nothing_yet'

export function permittedCopyStrength(posture: EvidencePosture): CopyStrength {
  if (posture.stormTier === 'E') return 'nothing_yet'
  if (posture.roofInspected && posture.hasPostStormImagery) return 'documented'
  // A storm is a reason to ask for a look. It is not a finding about a roof.
  if (posture.stormTier === 'A' || posture.stormTier === 'B' || posture.stormTier === 'C') {
    return 'storm_only'
  }
  return 'nothing_yet'
}
